---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: disk
      prompt: What is your USB device (eg /dev/sda)?
      private: no

  tasks:
    - name: check input
      assert:
        that:
          - disk is truthy
        fail_msg: "some values are not truthy"
        success_msg: "all values are truthy"
      any_errors_fatal: true

    - name: Adding Persistence to a Kali Linux "Live" USB Drive
      shell: |
        chmod o+x ./scripts/kali_psrt.zsh
        /bin/zsh ./scripts/kali_psrt.zsh {{ disk }}
      when: ansible_distribution is search("Kali")
      register: res
      ignore_errors: true

    - name: debug
      debug:
        var: res.stdout_lines
